agent_name = "aws-deepgram-workshop"
image = "YOUR_DOCKERHUB_USERNAME/aws-deepgram-workshop:0.1"
secret_set = "aws-deepgram-workshop-secrets"
image_credentials = "pull-secret"
[scaling]
	min_agents = 0
